---
- name: both gather facts is single file
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: this is first task without gather fact
      debug:
        msg: "{{ansible_os_family}}"
      gather_facts: no
...        
