---
- name: prompt variable
  hosts: all
  vars_prompt:
    - name: user_input
      prompt: "password"
  tasks:
    - name: first prompt file
      debug:
        msg: "{{user_input}}"
...            