---
- name: this playbook for tag
  hosts: all
  become: yes
  tasks:
    - name: this task is for redhat
      yum:
        name: httpd
        state: latest
      ignore_errors: yes
      tags: demo1

    - name: this task is for debian family
      apt:
        name: apache2
        state: latest
      ignore_errors: yes
      tags: demo2
...          

      